language: rust
sudo: true
rust:
  - stable
  - beta
  - nightly
  - 1.18.0
  - 1.17.0
os:
  - linux
  - osx
env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-C link-dead-code"
    - CARGO_MAKE_RUN_CODECOV=true
    - RUST_TEST_THREADS=1
script:
  - cargo install --debug cargo-make
  - cargo make ci-flow
