language: rust
sudo: true
rust:
  - stable
  - beta
  - nightly
  - 1.32.0
  - 1.31.0
  - 1.30.0
  - 1.29.0
  - 1.28.0
  - 1.27.0
  - 1.26.0
  - 1.25.0
  - 1.24.0
  - 1.23.0
  - 1.22.0
os:
  - linux
  - osx
env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-C link-dead-code"
    - CARGO_MAKE_RUN_CODECOV=true
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo install --debug cargo-make
  - cargo make ci-flow
