language: rust
sudo: true
rust:
  - stable
  - beta
  - nightly
  - 1.21.0
  - 1.20.0
os:
  - linux
  - osx
env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-C link-dead-code"
    - CARGO_MAKE_RUN_CODECOV=true
script:
  - cargo install --debug cargo-make
  - cargo run -- make ci-flow
