[package]
name = "cargo-make"
version = "0.7.4"
authors = ["Sagie Gur-Ari <sagiegurari@gmail.com>"]
description = "Rust task runner and build tool."
license = "Apache-2.0"
documentation = "https://sagiegurari.github.io/cargo-make"
homepage = "https://sagiegurari.github.io/cargo-make"
repository = "https://github.com/sagiegurari/cargo-make.git"
readme = "README.md"
keywords = ["task", "build", "cargo", "plugin", "subcommand"]
categories = ["development-tools", "development-tools::cargo-plugins", "development-tools::build-utils", "development-tools::testing"]
include = [
    "/benches/*",
    "/docs/*",
    "/examples/*",
    "/src/*",
    "/tests/*",
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/CHANGELOG.md",
    "/Makefile.toml"
]

[dependencies]
ci_info = "^0.1.12"
clap = "^2.27.1"
fern = "^0.4.3"
glob = "^0.2.11"
log = "^0.3.8"
rand = "^0.3.17"
run_script = "^0.1.5"
rust_info = "^0.1.8"
semver = "^0.9.0"
serde = "^1.0.17"
serde_derive = "^1.0.18"
shell2batch = "^0.1.6"
toml = "^0.4.5"

[features]
default = []

[badges.travis-ci]
branch = "master"
repository = "sagiegurari/cargo-make"

[badges.appveyor]
repository = "sagiegurari/cargo-make"
service = "github"
branch = "master"

[badges.codecov]
branch = "master"
repository = "sagiegurari/cargo-make"
service = "github"
