[package]
name = "cargo-make"
version = "0.5.1"
authors = ["Sagie Gur-Ari <sagiegurari@gmail.com>"]
description = "Rust task runner and build tool."
license = "Apache-2.0"
documentation = "https://sagiegurari.github.io/cargo-make"
homepage = "https://sagiegurari.github.io/cargo-make"
repository = "https://github.com/sagiegurari/cargo-make.git"
readme = "README.md"
keywords = ["task", "build", "cargo", "plugin", "subcommand"]
categories = ["development-tools", "development-tools::cargo-plugins", "development-tools::build-utils", "development-tools::testing"]
include = [
    "/benches/*",
    "/docs/*",
    "/examples/*",
    "/src/*",
    "/tests/*",
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/Makefile.toml"
]

[dependencies]
clap = "^2.26.0"
fern = "^0.4.2"
glob = "^0.2.11"
log = "^0.3.8"
rand = "^0.3.16"
semver = "0.8.0"
serde = "^1.0.12"
serde_derive = "^1.0.14"
toml = "^0.4.5"

[features]
default = []

[badges.travis-ci]
branch = "master"
repository = "sagiegurari/cargo-make"

[badges.appveyor]
repository = "sagiegurari/cargo-make"
service = "github"
branch = "master"

[badges.codecov]
branch = "master"
repository = "sagiegurari/cargo-make"
service = "github"
