[package]
name = "cargo-make"
version = "0.2.10"
authors = ["Sagie Gur-Ari <sagiegurari@gmail.com>"]
description = "Rust task runner and build tool."
license = "Apache-2.0"
documentation = "https://sagiegurari.github.io/cargo-make/api/cargo-make/index.html"
homepage = "http://github.com/sagiegurari/cargo-make"
repository = "https://github.com/sagiegurari/cargo-make.git"
readme = "README.md"
keywords = ["task", "build", "cargo", "plugin", "subcommand"]
categories = ["development-tools", "development-tools::cargo-plugins", "development-tools::build-utils", "development-tools::testing"]
include = [
    "**/*.rs",
    "src/*",
    "tests/*",
    "docs/*",
    "examples/*",
    "Cargo.toml",
    "LICENSE",
    "README.md",
    "Makefile.toml"
]

[dependencies]
clap = "^2.25.0"
rand = "^0.3.15"
serde = "^1.0.8"
serde_derive = "^1.0.8"
toml = "^0.4.2"

[features]
default = []

[badges.travis-ci]
branch = "master"
repository = "sagiegurari/cargo-make"

[badges.appveyor]
repository = "sagiegurari/cargo-make"
service = "github"
branch = "master"

[badges.codecov]
branch = "master"
repository = "sagiegurari/cargo-make"
service = "github"
