
[config]
additional_profiles = [
    "none-thread-safe-tests",
    "ci-coverage-tasks",
    "ci-all-build-tasks",
    "publish-pre-cleanup"
]

[env]
CARGO_MAKE_TEST_COVERAGE_BINARY_FILTER = "cli-[a-z0-9]*$\\|makers-[a-z0-9]*$\\|${CARGO_MAKE_TEST_COVERAGE_DEFAULT_BINARY_FILTER}"

[tasks.audit]
ignore_errors = true

[tasks.generate-readme]
script = [
'''
echo "generating readme file"
rm -f ./README.md
cat ./docs/_includes/README.md ./docs/_includes/nav.md ./docs/_includes/content.md >> README.md
sed -i 's,https://github.com/sagiegurari/cargo-make/blob/master/.github,.github,g' ./README.md
sed -i "s,{{ site.version }},${CARGO_MAKE_CRATE_VERSION},g" ./README.md
'''
]

[tasks.generate-task-list]
command = "cargo"
args = [
  "run",
  "--bin",
  "cargo-make",
  "--",
  "make",
  "--list-all-steps",
  "--output-format",
  "markdown-single-page",
  "--output-file",
  "${CARGO_MAKE_WORKING_DIRECTORY}/docs/cargo_make_task_list.md",
  "--makefile",
  "${CARGO_MAKE_WORKING_DIRECTORY}/src/lib/test/makefiles/empty.toml"
]

[tasks.generate-docs]
condition = { env_false = [ "CARGO_MAKE_CI" ], platforms = [ "linux" ] }
run_task = { name = ["generate-readme", "generate-task-list"] }

[tasks.post-docs]
linux_alias = "generate-docs"
