
[tasks.echo]
script = ["echo hello from member2"]

[tasks.member-only]
script = ["echo member 2"]

[tasks.workspace_root]
script = ["echo member 1 found root at: CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY=${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}"]

