
[tasks.env]
script = '''
echo CARGO_MAKE_CURRENT_TASK_NAME: ${CARGO_MAKE_CURRENT_TASK_NAME}
echo CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE: ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE}
echo CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY: ${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}
'''

[tasks.cwd]
command = "pwd"
condition_script = [
    "echo pwd during condition:",
    "pwd"
]
install_script = [
    "echo pwd during installation:",
    "pwd"
]

[tasks.change-cwd]
command = "pwd"
cwd = "./examples/files"
condition_script = [
    "echo pwd during condition:",
    "pwd"
]
install_script = [
    "echo pwd during installation:",
    "pwd"
]

[tasks.makefile-cwd]
command = "pwd"
cwd = "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}"
condition_script = [
    "echo pwd during condition:",
    "pwd"
]
install_script = [
    "echo pwd during installation:",
    "pwd"
]

[tasks.back-again]
alias = "cwd"

[tasks.all]
dependencies = ["env", "cwd", "change-cwd", "makefile-cwd", "back-again"]
