
[tasks.duckscript]
script_runner = "@duckscript"
script = [
'''
echo Hello World!
'''
]

[tasks.duckscript-example]
script_runner = "@duckscript"
script = [
'''
task_name = get_env CARGO_MAKE_CURRENT_TASK_NAME
echo The currently running cargo make task is: ${task_name}
cd .. # this changes cargo-make current working directory (cargo-make will revert to original directory after script execution)
pwd
set_env CARGO_MAKE_CURRENT_TASK_NAME tricking_cargo_make
'''
]

[tasks.duckscript-shebang-example]
script = [
'''
#!@duckscript
echo Running duckscript without runner attribute.
'''
]
