
[config]
skip_core_tasks = true

[env]
MULTIPLE_VALUES = "1|2|3|4"
TRIM_VALUE = "   123    "
CARGO_MAKE_CLIPPY_ARGS = ""

[env.ci]
CARGO_MAKE_CLIPPY_ARGS = "--all-features -- -D warnings"

[tasks.split]
command = "echo"
args = ["@@split(MULTIPLE_VALUES,|)"]

[tasks.no-split]
command = "echo"
args = ["${MULTIPLE_VALUES}"]

[tasks.remove-empty]
command = "echo"
args = ["1", "@@remove-empty(DOES_NOT_EXIST)", "2"]

[tasks.trim]
command = "echo"
args = ["@@trim(TRIM_VALUE)"]

[tasks.trim-start]
command = "echo"
args = ["@@trim(TRIM_VALUE,start)"]

[tasks.trim-end]
command = "echo"
args = ["@@trim(TRIM_VALUE,end)"]

[tasks.clippy]
command = "echo"
args = ["clippy", "@@split(CARGO_MAKE_CLIPPY_ARGS, )"]

[tasks.decode]
command = "echo"
args = ["Env:", "${DECODE_ENV_VAR}", "Decoded:", "@@decode(DECODE_ENV_VAR,development,dev,ci,test)"]

[tasks.decode-with-default]
command = "echo"
args = ["Env:", "${DECODE_ENV_VAR}", "Decoded:", "@@decode(DECODE_ENV_VAR,development,dev,ci,test,unknown)"]

[tasks.decode-with-eval]
command = "echo"
args = ["Env:", "${DECODE_ENV_VAR}", "Decoded:", "@@decode(DECODE_ENV_VAR,test,The current profile is: ${CARGO_MAKE_PROFILE})"]
