
[env.legacy]
CARGO_MAKE_TEST_USE_MUTLI_TEST_PHASES = "old"

[env.new]
CARGO_MAKE_TEST_USE_MULTI_TEST_PHASES = "new"

[tasks.print-migrated-env]
script = '''
#!@duckscript

echo CARGO_MAKE_TEST_USE_MULTI_TEST_PHASES ${CARGO_MAKE_TEST_USE_MULTI_TEST_PHASES}
echo CARGO_MAKE_TEST_USE_MUTLI_TEST_PHASES ${CARGO_MAKE_TEST_USE_MUTLI_TEST_PHASES}
'''
