
[config]
skip_core_tasks = true
on_error_task = "catch"

[tasks.default]
dependencies = ["echo", "error"]

[tasks.echo]
command = "echo"
args = ["args:", "${@}"]

[tasks.error]
script = "exit 1"

[tasks.catch]
script = '''
echo "Doing cleanups in catch"
'''
