
[config]
skip_core_tasks = true

[tasks.default]
dependencies = ["hello-world-common", "hello-world"]

[tasks.hello-world-common]
script = [
    "echo \"Hello World From All Platforms\""
]

[tasks.hello-world]
script = [
    "echo \"Hello World From Unknown\""
]

[tasks.hello-world.linux]
script = [
    "echo \"Hello World From Linux\""
]

