
[env]
COMMON = "COMMON"
PROFILE_NAME = "${CARGO_MAKE_PROFILE}"
CARGO_PROFILE_NAME = "${CARGO_MAKE_CARGO_PROFILE}"
IS_CI = false

[config]
additional_profiles = ["ci", "ci-all-tasks"]

[env.development]
IS_DEV = "TRUE"
IS_PROD = "FALSE"

[env.production]
IS_DEV = "FALSE"
IS_PROD = "TRUE"

[env.ci]
IS_CI = true

[tasks.echo]
script = '''
echo COMMON: ${COMMON}
echo PROFILE_NAME: ${PROFILE_NAME}
echo CARGO_PROFILE_NAME: ${CARGO_PROFILE_NAME}
echo IS_DEV: ${IS_DEV}
echo IS_PROD: ${IS_PROD}
echo IS_CI: ${IS_CI}


echo CARGO_MAKE_RUN_CHECK_FORMAT: ${CARGO_MAKE_RUN_CHECK_FORMAT}
echo CARGO_MAKE_RUN_BENCH: ${CARGO_MAKE_RUN_BENCH}
echo CARGO_MAKE_RUN_CLIPPY: ${CARGO_MAKE_RUN_CLIPPY}
echo CARGO_MAKE_RUN_CODECOV: ${CARGO_MAKE_RUN_CODECOV}
'''

[tasks.echo-development]
condition = { profiles = [ "development" ] }
command = "echo"
args = [ "running in development profile" ]

[tasks.echo-production]
condition = { profiles = [ "production" ] }
command = "echo"
args = [ "running in production profile" ]
