
[config]
skip_core_tasks = true

[tasks.hello-world]
script = [
    "echo start...",
    "echo \"Hello World From Script\"",
    "echo end..."
]

[tasks.hello-world-from-script-file]
script = { file = "script.sh" }

[tasks.hello-world-from-script-file-absolute-path]
script = { file = "${CARGO_MAKE_WORKING_DIRECTORY}/script.sh", absolute_path = true }

[tasks.default]
dependencies = ["hello-world"]
