
[tasks.shebang-sh]
script = [
'''
#!/bin/bash
echo hello
'''
]

[tasks.shebang-sh-arg]
script = [
'''
#!/usr/bin/env bash
echo hello
'''
]

[tasks.shebang-python]
script = [
'''
#!/usr/bin/env python3
print("Hello, World!")
'''
]
