[tasks.format]
install_create = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--write-mode=overwrite"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
depedencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
depedencies = ["clean"]

[tasks.my-flow]
depedencies = [
    "format",
    "build",
    "test"
]