
[env]
NIGHTLY_VERSION = "2019-07-16"

[tasks.rustc-version-stable]
toolchain = "stable"
command = "rustc"
args = ["--version"]

[tasks.rustc-version-stable-edition-2021]
toolchain = { channel = "stable", min_version = "1.56" }
command = "rustc"
args = ["--version"]

[tasks.rustc-version-nightly]
toolchain = "nightly"
command = "rustc"
args = ["--version"]

[tasks.rustc-version-flow]
dependencies = [
  "rustc-version-stable",
  "rustc-version-stable-edition-2021",
  "rustc-version-nightly",
]

[tasks.echo-cargo-env]
script = '''
echo CARGO=${CARGO}
echo RUSTC=${RUSTC}
echo RUSTDOC=${RUSTDOC}
echo RUSTFLAGS=${RUSTFLAGS}
'''

[tasks.echo-cargo-stable]
extend = "echo-cargo-env"
toolchain = "stable"

[tasks.stable]
alias = "echo-cargo-stable"

[tasks.echo-cargo-nightly]
extend = "echo-cargo-env"
toolchain = "nightly"

[tasks.nightly]
alias = "echo-cargo-nightly"

[tasks.echo-cargo-all]
dependencies = ["echo-cargo-stable", "echo-cargo-nightly"]

[tasks.with_env_vars]
toolchain = "nightly-${NIGHTLY_VERSION}"
command = "rustc"
args = ["--version"]

[tasks.empty_value]
toolchain = ""
command = "rustc"
args = ["--version"]
