
[tasks.varargs]
command = "echo"
args = ["args are:", "${@}"]

[tasks.varargs-template]
command = "echo"
args = ["args are:", "-o=${@}"]

[tasks.cli-args]
script = "echo args are: ${@}"

[tasks.cli-args-shell]
script_runner = "@shell"
script = "echo args are: ${@}"

[tasks.cli-args-rust]
script_runner = "@rust"
script = '''
use std::env;
fn main() {
    let args: Vec<String> = env::args().collect();
    println!("args are: {:?}", args);
}
'''
