
[tasks.echo]
script = ["echo hello from member1"]

[tasks.workspace_root]
script = [
  "echo member 1 found root at: CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY=${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}",
]
